# Generated by Django 5.0.3 on 2024-04-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tTitle',
            new_name='title',
        ),
    ]
